### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by AtomB78** [phobos927/AutoTargetInCombatOnly#1]
This has stopped working for me. It was still send the notifications in chat that it's on or off, however It's no longer functioning the way it did originally I'm no longer able to soft target enemies in combat. Disabled all my addons and tried it without anything and it still  doesn't work.

**Comment by phobos927** [comment]
> This has stopped working for me. It was still send the notifications in chat that it's on or off, however It's no longer functioning the way it did originally I'm no longer able to soft target enemies in combat. Disabled all my addons and tried it without anything and it still doesn't work.

Thank you. Updated version. In case of problems, please report. <3
